$schema: "https://json-schema.org/draft/2020-12/schema"
$id: "training-config.schema.json"
title: "Training Config Schema"
title_es: "Esquema de Configuración de Entrenamiento"
type: object
additionalProperties: false
required:
  - training

properties:
  base_model:
    $ref: "schema/_base_model.yaml"
  tokenizer:
    $ref: "schema/_tokenizer.yaml"
  model_class:
    $ref: "schema/_model_class.yaml"
  model:
    $ref: "schema/_model.yaml"
  training:
    $ref: "schema/_training.yaml"

allOf:
  $ref: "schema/_conditional_rules.yaml"

examples:
  $ref: "schema/_examples.yaml"
